#!/usr/bin/ruby

require 'fileutils'

APP_DIR = File::dirname(File.expand_path(File.dirname(__FILE__)))
RES_DIR = File::join(APP_DIR, "pkg_resources")

def install_console_helper(console_helper_name, target_cmd_name)
    etc_dir = ENV['sysconf_dir'] || ENV['etc_dir'] || '/etc'

    console_helper_link = File.join(APP_DIR, 'bin', console_helper_name)
    cmd_path = File.join(APP_DIR, 'bin', target_cmd_name)
    pam_src_path = File.join( RES_DIR, console_helper_name + '.pam' )
    pam_dst_path = File.join(etc_dir, 'pam.d', console_helper_name)
    console_app_file = File.join(etc_dir, 'security', 'console.apps', console_helper_name)
    console_helper_target = %x{ which consolehelper }.strip!

    if !console_helper_target then
        puts <<-EOF

consolehelper is not installed.
install usermode package and try again.
EOF
        exit 1
    end

    puts "cp #{pam_src_path} #{pam_dst_path}"
    puts "ln -s #{console_helper_target}  #{console_helper_link}"
    puts "write #{console_app_file}"

    FileUtils.cp(pam_src_path, pam_dst_path)
    if File.exist?(console_helper_link) then
        File.unlink(console_helper_link)
    end
    File.symlink(console_helper_target, console_helper_link)
    FileUtils.mkdir_p(File.dirname(console_app_file))

    open(console_app_file, 'w') do |f|
        f.write(<<-EOF
USER=root
PROGRAM=#{cmd_path}
FALLBACK=false
SESSION=true
EOF
               )
    end
end

desc "Install consolehelper files."
task :install_consolehelper do
    install_console_helper('gemcmdwin-super.rb', 'gemcmdwin.rb')
end

desc "Install Application Menu"
task :install_menu do
    menuDir = %x{ kde4-config --install xdgdata-apps }.strip
    menuEntryFile = File.join(menuDir, 'kgem.desktop')
    open(menuEntryFile,'w') do |f|
        f.write(<<-EOF
[Desktop Entry]
Name=Kgem
Comment=Ruby Gem Tool with KDE GUI
Exec=kgem.rb %f
Icon=kgem
Terminal=false
Type=Application
Categories=Qt;KDE;Utility;
MimeType=application/x-gem;
    EOF
               )
        %x{ update-menus }
    end
end

task :default => [ :install_consolehelper, :install_menu  ]
